[project]
name = "rl-secret-hitler"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "modal>=1.2.1",
    "openai>=2.7.1",
    "pydantic>=2.12.4",
    "pydantic-settings>=2.11.0",
]
